### ISSUE TITLE
i cant add color roles?

### ISSUE THREAD

**Issue by SunRise-ppl** [DamourYouKnow/damour-bot#12]
im having trouble using the colored roles commands

mainly adding a color

**Comment by DamourYouKnow** [comment]
Hello,

Before using the assignable colors feature the roles must first be created using the prefix defined by the `colorPrefix` property in the `config.yml` file. For example, using the default prefix `color.`, you can create the roles `color.red` and `color.blue`. These roles will then show up in the list of assignable colors.

For this feature to work please make sure the bot client is given the permission to manage roles. I will update the README file with this information soon.

I hope this helps. Let me know if you are still having issues.

**Comment by SunRise-ppl** [comment]
thank u for the help i got it working
